### ISSUE TITLE
Method `isWithBody()` dont exists

### ISSUE THREAD

**Issue by wallysoncarvalho** [OpenFeign/feign#1873]
I just updated `feign-okhttp` from `11.9.1` to `12.1` and started getting the following error: `java.lang.NoSuchMethodError: 'boolean feign.Request$HttpMethod.isWithBody()'`. While debugging i noticed that is being used [here](https://github.com/OpenFeign/feign/blob/master/okhttp/src/main/java/feign/okhttp/OkHttpClient.java#L80),so when opening the class `OkHttpClient` there's an error of the method that couldn't be found.

related dependencies are:

```
implementation("org.springframework.cloud:spring-cloud-starter-openfeign")
implementation("io.github.openfeign:feign-okhttp:$feignOkHttpVersion") {
    exclude(module = "okhttp3")
}
implementation("com.squareup.okhttp3:okhttp:4.10.0")
```

**Comment by velo** [comment]
Seems the issue is related to using a different version of okhttp.

**Comment by dbubenheim** [comment]
Today I faced the same issue. Did you came up with a solution yet?

**Comment by zhad3** [comment]
Also faced this issue today after upgrading feign-okhttp to v12.
The method `feign.Request$HttpMethod.isWithBody()` is available in feign-core v12. In our setup we use `spring-cloud-starter-openfeign (spring-cloud 2021.0.5)` with `spring-boot (2.7.8)`.

`feign-core v12` is only available with `spring-cloud (2022.0.x)` and `spring-boot (3.0.x)`. We have downgraded `feign-okhttp` to v11.10 for now until we upgrade spring.

**Comment by toritsejuFO** [comment]
Thanks a lot. Had me pulling my hair out. Used 12.1 because it seemed to align in terms of when SpringBoot 2.7.7 came out.
